### ISSUE TITLE
Notebooks-as-code with Jupytext

### ISSUE THREAD

**Issue by edoardob90** [empa-scientific-it/python-tutorial#307]
[Jupytext](https://jupytext.readthedocs.io/en/latest/install.html) is a package and Jupyter extension that provides a very useful way of "pairing" a notebook with a text file in many formats: a Python script, a Markdown, a RestructuredText.

[Pairing](https://jupytext.readthedocs.io/en/latest/paired-notebooks.html) a notebook from Jupyter creates the chosen text file alongside the notebook file. Any changes made to the text file are reflected in the notebook upon reloading.

I think this is an incredibly useful addition to simplify reviews on GitHub because you can change or suggest changes **directly** on a text file, instead of an IPython notebook (which is an unreadable JSON).

The notebook and the text file are synced **only on save**: if you don't reload and save the notebook from Jupyter, the changes are not synced. An even more useful addition is to integrate Jupytext syncing as a [pre-commit hook](https://jupytext.readthedocs.io/en/latest/using-pre-commit.html):

```yaml
repos:
-   repo: https://github.com/mwouts/jupytext
    rev: v1.14.7  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--sync]
```

### Todo

- [ ] Add `jupytext` as a dependency
- [ ] Enable the JupyterLab extension (Dockerfile)
- [ ] Setup a pre-commit hook
