### ISSUE TITLE
Cleanup notebook from Quarto slides annotations

### ISSUE THREAD

**Issue by yakutovicha** [empa-scientific-it/python-tutorial#51]
Also, make sure to fix highlights.

**Comment by edoardob90** [comment]
The `input_output.ipynb` needs some cleanup as well. The lines in the frontmatter

```
---
title: "Input and output"
format: revealjs
callout-icon: false
jupyter: python3
highlight-style: dracula
execute:
    echo: true
    enabled: false
---
```

should be removed. They're only relevant for slides created with Quarto.
